title: Default
"@extends":
  type: default
  context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          fields:
            header.kota.subheading:
              type: text
              label: Subheading
