title: Default
"@extends":
  type: default
  context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          fields:
            content:
              ordering@: 4

            header.media_order:
              ordering@: 5

            header.kota.subheading:
              type: text
              label: Subheading
